// Code generated by wiregen from internal/wiregen/schema.json. DO NOT EDIT.

package wire

import (
	"encoding/binary"
	"errors"
	"fmt"
	"math"
)

const (
	// ProtocolVersion is the exact transport version accepted by every peer.
	ProtocolVersion uint16 = 2
	// DefaultMaxFrame caps one length-prefixed frame at 4 MiB.
	DefaultMaxFrame = 4194304
	frameHeaderSize = 32
	framePrefixSize = 4
)

var frameMagic = [4]byte{'D', 'K', 'S', '1'}

var (
	// ErrFrameTooLarge means a declared frame exceeds DefaultMaxFrame.
	ErrFrameTooLarge = errors.New("wire: frame exceeds maximum")
	// ErrFrameTruncated means a packet ends in the middle of a frame.
	ErrFrameTruncated = errors.New("wire: truncated frame")
	// ErrProtocolVersion means a frame carries a protocol other than ProtocolVersion.
	ErrProtocolVersion = errors.New("wire: unsupported protocol version")
	// ErrInvalidFrame means a frame violates the structural contract.
	ErrInvalidFrame = errors.New("wire: invalid frame")
)

// FrameKind identifies one session message.
type FrameKind uint8

const (
	// FrameHello begins the session handshake.
	FrameHello FrameKind = 1
	// FrameHelloAck accepts the session handshake.
	FrameHelloAck FrameKind = 2
	// FrameRequest starts one request.
	FrameRequest FrameKind = 3
	// FrameResponse completes one request.
	FrameResponse FrameKind = 4
	// FrameCancel cancels one request.
	FrameCancel FrameKind = 5
	// FrameEvent pushes one session event.
	FrameEvent FrameKind = 6
	// FrameStream carries one ordered stream chunk.
	FrameStream FrameKind = 7
	// FrameGoAway requests or acknowledges settled session closure.
	FrameGoAway FrameKind = 8
	// FrameWindow grants one stream additional bounded-delivery credits.
	FrameWindow FrameKind = 9
	// FrameAck confirms that a terminal response reached the client.
	FrameAck FrameKind = 10
	// FrameLifecycle carries one daemon-owned lifecycle snapshot.
	FrameLifecycle FrameKind = 11
)

// FrameFlags modifies a frame without changing its kind.
type FrameFlags uint8

const (
	// FlagEnd marks the final payload in a request or response stream.
	FlagEnd FrameFlags = 1
)

// Op names a control-plane operation. Consumers define their own op values.
type Op string

// Frame is the transport's fixed-header message. Payload stays opaque to wire.
type Frame struct {
	Kind              FrameKind
	Flags             FrameFlags
	ID                uint64
	Sequence          uint32
	DeadlineUnixMilli int64
	Op                Op
	Tenant            string
	Payload           []byte
}

func (k FrameKind) valid() bool { return k >= FrameHello && k <= FrameLifecycle }

// EncodeFrame encodes one structurally valid frame body without its length prefix.
func EncodeFrame(frame Frame) ([]byte, error) {
	if !frame.Kind.valid() {
		return nil, fmt.Errorf("%w: kind %d", ErrInvalidFrame, frame.Kind)
	}
	if frame.Flags&^FlagEnd != 0 {
		return nil, fmt.Errorf("%w: flags %d", ErrInvalidFrame, frame.Flags)
	}
	if len(frame.Op) > math.MaxUint16 {
		return nil, fmt.Errorf("%w: operation length %d", ErrInvalidFrame, len(frame.Op))
	}
	if len(frame.Tenant) > math.MaxUint16 {
		return nil, fmt.Errorf("%w: tenant length %d", ErrInvalidFrame, len(frame.Tenant))
	}
	if frame.DeadlineUnixMilli < 0 {
		return nil, fmt.Errorf("%w: negative deadline %d", ErrInvalidFrame, frame.DeadlineUnixMilli)
	}
	body := make([]byte, frameHeaderSize+len(frame.Op)+len(frame.Tenant)+len(frame.Payload))
	copy(body[:4], frameMagic[:])
	binary.BigEndian.PutUint16(body[4:6], ProtocolVersion)
	body[6] = byte(frame.Kind)
	body[7] = byte(frame.Flags)
	binary.BigEndian.PutUint64(body[8:16], frame.ID)
	binary.BigEndian.PutUint32(body[16:20], frame.Sequence)
	binary.BigEndian.PutUint64(body[20:28], uint64(frame.DeadlineUnixMilli))
	binary.BigEndian.PutUint16(body[28:30], uint16(len(frame.Op)))
	binary.BigEndian.PutUint16(body[30:32], uint16(len(frame.Tenant)))
	off := frameHeaderSize
	off += copy(body[off:], frame.Op)
	off += copy(body[off:], frame.Tenant)
	copy(body[off:], frame.Payload)
	return body, nil
}

// DecodeFrame decodes one version-exact frame body without its length prefix.
func DecodeFrame(body []byte) (Frame, error) {
	if len(body) < frameHeaderSize {
		return Frame{}, fmt.Errorf("%w: body length %d", ErrInvalidFrame, len(body))
	}
	if string(body[:4]) != string(frameMagic[:]) {
		return Frame{}, fmt.Errorf("%w: magic", ErrInvalidFrame)
	}
	version := binary.BigEndian.Uint16(body[4:6])
	if version != ProtocolVersion {
		return Frame{}, fmt.Errorf("%w: got %d, want %d", ErrProtocolVersion, version, ProtocolVersion)
	}
	kind := FrameKind(body[6])
	if !kind.valid() {
		return Frame{}, fmt.Errorf("%w: kind %d", ErrInvalidFrame, kind)
	}
	flags := FrameFlags(body[7])
	if flags&^FlagEnd != 0 {
		return Frame{}, fmt.Errorf("%w: flags %d", ErrInvalidFrame, flags)
	}
	deadline := binary.BigEndian.Uint64(body[20:28])
	if deadline > math.MaxInt64 {
		return Frame{}, fmt.Errorf("%w: deadline %d exceeds int64", ErrInvalidFrame, deadline)
	}
	opLength := int(binary.BigEndian.Uint16(body[28:30]))
	tenantLength := int(binary.BigEndian.Uint16(body[30:32]))
	if frameHeaderSize+opLength+tenantLength > len(body) {
		return Frame{}, fmt.Errorf("%w: routing lengths", ErrInvalidFrame)
	}
	off := frameHeaderSize
	op := Op(body[off : off+opLength])
	off += opLength
	tenant := string(body[off : off+tenantLength])
	off += tenantLength
	return Frame{
		Kind:              kind,
		Flags:             flags,
		ID:                binary.BigEndian.Uint64(body[8:16]),
		Sequence:          binary.BigEndian.Uint32(body[16:20]),
		DeadlineUnixMilli: int64(deadline),
		Op:                op,
		Tenant:            tenant,
		Payload:           append([]byte(nil), body[off:]...),
	}, nil
}

// EncodePacket encodes one frame as a length-prefixed packet under DefaultMaxFrame.
func EncodePacket(frame Frame) ([]byte, error) {
	body, err := EncodeFrame(frame)
	if err != nil {
		return nil, err
	}
	if len(body) > DefaultMaxFrame {
		return nil, fmt.Errorf("%w: %d > %d", ErrFrameTooLarge, len(body), DefaultMaxFrame)
	}
	packet := make([]byte, framePrefixSize+len(body))
	binary.BigEndian.PutUint32(packet[:framePrefixSize], uint32(len(body)))
	copy(packet[framePrefixSize:], body)
	return packet, nil
}

// DecodePacket decodes one exact length-prefixed packet under DefaultMaxFrame.
func DecodePacket(packet []byte) (Frame, error) {
	if len(packet) < framePrefixSize {
		return Frame{}, ErrFrameTruncated
	}
	declared := int(binary.BigEndian.Uint32(packet[:framePrefixSize]))
	if declared > DefaultMaxFrame {
		return Frame{}, fmt.Errorf("%w: %d > %d", ErrFrameTooLarge, declared, DefaultMaxFrame)
	}
	body := packet[framePrefixSize:]
	if len(body) < declared {
		return Frame{}, ErrFrameTruncated
	}
	if len(body) > declared {
		return Frame{}, fmt.Errorf("%w: %d trailing bytes", ErrInvalidFrame, len(body)-declared)
	}
	return DecodeFrame(body)
}
