// Code generated by wire/lifeproto/gen; DO NOT EDIT.

import Foundation

public extension DaemonKit {
    /// Version of the daemonkit-native lifecycle envelope (`"v"` in every flat
    /// frame). Generated from the shared lifeproto schema; the Go side pins the
    /// same `Version`.
    static let lifeProtocolVersion = 1
}

/// A canonical lifecycle operation carried in a message's `op` field.
public enum LifecycleOp: String, Sendable, CaseIterable {
    case health
    case shutdown
    case hello
    case handoff
}

/// Assembles flat lifecycle frames in Go's `json.Marshal` field order
/// with Go-compatible string escaping, so the Swift bytes match the Go peer
/// exactly. Foundation's JSONEncoder is not used to encode: it does not preserve
/// key order.
enum LifecycleJSON {
    static func object(_ members: [(String, String)]) -> Data {
        var out = "{"
        for (index, member) in members.enumerated() {
            if index > 0 { out += "," }
            out += escape(member.0) + ":" + member.1
        }
        out += "}"
        return Data(out.utf8)
    }

    static func string(_ value: String) -> String { escape(value) }

    static func int(_ value: Int) -> String { String(value) }

    static func bool(_ value: Bool) -> String { value ? "true" : "false" }

    static func strings(_ values: [String]) -> String {
        "[" + values.map(escape).joined(separator: ",") + "]"
    }

    // Mirrors encoding/json HTML-safe escaping so the Swift bytes match the
    // Go peer for any string value (quotes, backslash, control, and HTML bytes).
    static func escape(_ value: String) -> String {
        var out = "\""
        for scalar in value.unicodeScalars {
            switch scalar {
            case "\"": out += "\\\""
            case "\\": out += "\\\\"
            case "\n": out += "\\n"
            case "\r": out += "\\r"
            case "\t": out += "\\t"
            case "<": out += "\\u003c"
            case ">": out += "\\u003e"
            case "&": out += "\\u0026"
            case "\u{2028}": out += "\\u2028"
            case "\u{2029}": out += "\\u2029"
            default:
                if scalar.value < 0x20 {
                    out += String(format: "\\u%04x", scalar.value)
                } else {
                    out.unicodeScalars.append(scalar)
                }
            }
        }
        out += "\""
        return out
    }
}

/// A flat lifecycle message: the shared `{v, op}` header plus op-specific
/// fields, exchanged as one JSON object per line (the transport appends the
/// framing `\n`).
public protocol LifecycleMessage: Decodable, Sendable {
    /// The single-line JSON encoding of this message, without the framing `\n`.
    func encoded() -> Data
}

public extension LifecycleMessage {
    /// Decodes a message from a single JSON frame (newline already stripped).
    static func decode(from data: Data) throws -> Self {
        try JSONDecoder().decode(Self.self, from: data)
    }
}

/// A decoded frame whose protocol version is not ``DaemonKit/lifeProtocolVersion``.
public enum LifecycleWireError: Error, Sendable {
    case unsupportedProtocolVersion(Int)
}

/// The `{v, op}` header every message begins with; ``decode(from:)`` reads it to
/// dispatch on `op` before the concrete message type is known.
public struct Envelope: Decodable, Sendable {
    public let v: Int
    public let op: String

    /// Decodes the header and rejects a foreign protocol version with
    /// ``LifecycleWireError/unsupportedProtocolVersion(_:)``.
    public static func decode(from data: Data) throws -> Envelope {
        let envelope = try JSONDecoder().decode(Envelope.self, from: data)
        guard envelope.v == DaemonKit.lifeProtocolVersion else {
            throw LifecycleWireError.unsupportedProtocolVersion(envelope.v)
        }
        return envelope
    }
}

/// HealthRequest asks the peer for its health snapshot.
public struct HealthRequest: LifecycleMessage {
    public let v: Int
    public let op: String

    /// Builds a health request at the current protocol version.
    public init() {
        v = DaemonKit.lifeProtocolVersion
        op = LifecycleOp.health.rawValue
    }

    public func encoded() -> Data {
        LifecycleJSON.object([
            ("v", LifecycleJSON.int(v)),
            ("op", LifecycleJSON.string(op)),
        ])
    }
}

/// HealthResponse is the peer's health snapshot. Features is the only source of capability truth — never a version compare.
public struct HealthResponse: LifecycleMessage {
    public let v: Int
    public let op: String
    /// The peer's own build version. Never compared for capability — Features is the only source of capability truth.
    public let version: String
    /// The peer's process id.
    public let pid: Int
    /// The peer's lifecycle state, e.g. "healthy" or "degraded".
    public let state: String
    /// Whether the peer is draining.
    public let draining: Bool
    /// Whether the peer is serving work.
    public let busy: Bool
    /// The peer's advertised feature bits; the sole source of capability truth.
    public let features: [String]

    /// Builds a health snapshot; a nil features slice encodes as [].
    public init(version: String, pid: Int, state: String, draining: Bool, busy: Bool, features: [String]) {
        v = DaemonKit.lifeProtocolVersion
        op = LifecycleOp.health.rawValue
        self.version = version
        self.pid = pid
        self.state = state
        self.draining = draining
        self.busy = busy
        self.features = features
    }

    public func encoded() -> Data {
        LifecycleJSON.object([
            ("v", LifecycleJSON.int(v)),
            ("op", LifecycleJSON.string(op)),
            ("version", LifecycleJSON.string(version)),
            ("pid", LifecycleJSON.int(pid)),
            ("state", LifecycleJSON.string(state)),
            ("draining", LifecycleJSON.bool(draining)),
            ("busy", LifecycleJSON.bool(busy)),
            ("features", LifecycleJSON.strings(features)),
        ])
    }
}

/// ShutdownRequest asks the peer to shut down.
public struct ShutdownRequest: LifecycleMessage {
    public let v: Int
    public let op: String

    /// Builds a shutdown request.
    public init() {
        v = DaemonKit.lifeProtocolVersion
        op = LifecycleOp.shutdown.rawValue
    }

    public func encoded() -> Data {
        LifecycleJSON.object([
            ("v", LifecycleJSON.int(v)),
            ("op", LifecycleJSON.string(op)),
        ])
    }
}

/// ShutdownResponse acknowledges a shutdown request.
public struct ShutdownResponse: LifecycleMessage {
    public let v: Int
    public let op: String
    /// Whether the peer accepted the request.
    public let ok: Bool

    /// Builds a shutdown acknowledgement.
    public init(ok: Bool) {
        v = DaemonKit.lifeProtocolVersion
        op = LifecycleOp.shutdown.rawValue
        self.ok = ok
    }

    public func encoded() -> Data {
        LifecycleJSON.object([
            ("v", LifecycleJSON.int(v)),
            ("op", LifecycleJSON.string(op)),
            ("ok", LifecycleJSON.bool(ok)),
        ])
    }
}

/// HelloRequest opens the capability handshake.
public struct HelloRequest: LifecycleMessage {
    public let v: Int
    public let op: String

    /// Builds a hello request.
    public init() {
        v = DaemonKit.lifeProtocolVersion
        op = LifecycleOp.hello.rawValue
    }

    public func encoded() -> Data {
        LifecycleJSON.object([
            ("v", LifecycleJSON.int(v)),
            ("op", LifecycleJSON.string(op)),
        ])
    }
}

/// HelloResponse announces the peer's advertised feature bits.
public struct HelloResponse: LifecycleMessage {
    public let v: Int
    public let op: String
    /// The peer's advertised feature bits; the sole source of capability truth.
    public let features: [String]

    /// Builds a hello announcement; a nil features slice encodes as [].
    public init(features: [String]) {
        v = DaemonKit.lifeProtocolVersion
        op = LifecycleOp.hello.rawValue
        self.features = features
    }

    public func encoded() -> Data {
        LifecycleJSON.object([
            ("v", LifecycleJSON.int(v)),
            ("op", LifecycleJSON.string(op)),
            ("features", LifecycleJSON.strings(features)),
        ])
    }
}

/// HandoffRequest asks the peer to release its socket for a successor.
public struct HandoffRequest: LifecycleMessage {
    public let v: Int
    public let op: String

    /// Builds a handoff request.
    public init() {
        v = DaemonKit.lifeProtocolVersion
        op = LifecycleOp.handoff.rawValue
    }

    public func encoded() -> Data {
        LifecycleJSON.object([
            ("v", LifecycleJSON.int(v)),
            ("op", LifecycleJSON.string(op)),
        ])
    }
}

/// HandoffResponse acknowledges a handoff request.
public struct HandoffResponse: LifecycleMessage {
    public let v: Int
    public let op: String
    /// Whether the peer accepted the request.
    public let ok: Bool

    /// Builds a handoff acknowledgement.
    public init(ok: Bool) {
        v = DaemonKit.lifeProtocolVersion
        op = LifecycleOp.handoff.rawValue
        self.ok = ok
    }

    public func encoded() -> Data {
        LifecycleJSON.object([
            ("v", LifecycleJSON.int(v)),
            ("op", LifecycleJSON.string(op)),
            ("ok", LifecycleJSON.bool(ok)),
        ])
    }
}
