import Darwin
import Foundation

// wiregen:begin
// Code generated by wiregen from internal/wiregen/schema.json. DO NOT EDIT.

/// Exact protocol version shared by daemonkit's Go and Swift session transports.
public let daemonKitSessionProtocolVersion: UInt16 = 2

/// Default maximum encoded frame body: 4 MiB.
public let daemonKitDefaultMaximumFrameBytes = 4_194_304

/// A session frame kind.
public enum SessionFrameKind: UInt8, Sendable {
    case hello = 1
    case helloAck = 2
    case request = 3
    case response = 4
    case cancel = 5
    case event = 6
    case stream = 7
    case goAway = 8
    case window = 9
    case acknowledgment = 10
    case lifecycle = 11
}

/// Flags carried by a session frame.
public struct SessionFrameFlags: OptionSet, Sendable {
    public let rawValue: UInt8

    public init(rawValue: UInt8) {
        self.rawValue = rawValue
    }

    /// Marks the final request or response stream payload.
    public static let end = SessionFrameFlags(rawValue: 1)
}

extension SessionFrameCodec {
    static let headerBytes = 32
    static let magic = Data("DKS1".utf8)

    static func encode(_ frame: SessionFrame) throws -> Data {
        try validate(frame)
        let operation = Data(frame.operation.utf8)
        let tenant = Data(frame.tenant.utf8)
        guard operation.count <= Int(UInt16.max), tenant.count <= Int(UInt16.max) else {
            throw SessionTransportError.invalidFrame("routing field too long")
        }
        var body = Data()
        body.append(magic)
        body.appendUInt16(daemonKitSessionProtocolVersion)
        body.append(frame.kind.rawValue)
        body.append(frame.flags.rawValue)
        body.appendUInt64(frame.id)
        body.appendUInt32(frame.sequence)
        body.appendUInt64(UInt64(bitPattern: frame.deadlineUnixMilliseconds))
        body.appendUInt16(UInt16(operation.count))
        body.appendUInt16(UInt16(tenant.count))
        body.append(operation)
        body.append(tenant)
        body.append(frame.payload)
        return body
    }

    static func decode(_ body: Data) throws -> SessionFrame {
        guard body.count >= headerBytes else {
            throw SessionTransportError.invalidFrame("short header")
        }
        guard body.prefix(4) == magic else {
            throw SessionTransportError.invalidFrame("magic")
        }
        let version = body.uint16(at: 4)
        guard version == daemonKitSessionProtocolVersion else {
            throw SessionTransportError.unsupportedProtocolVersion(version)
        }
        guard let kind = SessionFrameKind(rawValue: body[6]) else {
            throw SessionTransportError.invalidFrame("kind")
        }
        let flags = SessionFrameFlags(rawValue: body[7])
        guard flags.subtracting(.end).isEmpty else {
            throw SessionTransportError.invalidFrame("flags")
        }
        let operationLength = Int(body.uint16(at: 28))
        let tenantLength = Int(body.uint16(at: 30))
        let routingEnd = headerBytes + operationLength + tenantLength
        guard routingEnd <= body.count else {
            throw SessionTransportError.invalidFrame("routing lengths")
        }
        let operationRange = headerBytes ..< headerBytes + operationLength
        let tenantRange = operationRange.upperBound ..< routingEnd
        guard let operation = String(data: body[operationRange], encoding: .utf8),
              let tenant = String(data: body[tenantRange], encoding: .utf8)
        else {
            throw SessionTransportError.invalidFrame("routing UTF-8")
        }
        let frame = SessionFrame(
            kind: kind,
            flags: flags,
            id: body.uint64(at: 8),
            sequence: body.uint32(at: 16),
            deadlineUnixMilliseconds: Int64(bitPattern: body.uint64(at: 20)),
            operation: operation,
            tenant: tenant,
            payload: body.subdata(in: routingEnd ..< body.count)
        )
        try validate(frame)
        return frame
    }
}

// wiregen:end

/// The two session kinds protocol 2 admits: the trust-gated control lane and
/// the schema-gated business lane.
public enum SessionLane: String, Codable, Sendable {
    /// The repair channel: drain and broker handoff, gated by control trust.
    case control
    /// The product channel: schema set-membership at attach.
    case business
}

/// The runtime lifecycle state the server publishes to every session.
public enum SessionPhase: String, Codable, Sendable {
    /// Pre-readiness; business dispatch is typed-rejected.
    case starting = "runtime_starting"
    /// Business dispatch is admitted.
    case ready = "runtime_ready"
    /// Intake is closing; reconnect elsewhere.
    case draining = "runtime_draining"
    /// The runtime's terminal failure.
    case failed = "runtime_failed"
}

/// One monotonic runtime lifecycle publication.
public struct PhaseSnapshot: Equatable, Sendable {
    public let sequence: UInt64
    public let phase: SessionPhase
    public let detail: Data?

    public init(sequence: UInt64, phase: SessionPhase, detail: Data? = nil) {
        self.sequence = sequence
        self.phase = phase
        self.detail = detail
    }
}

/// The server answered the handshake with the drain preamble instead of an ack.
public struct SessionDrainingError: Error, Equatable, Sendable {
    public init() {}
}

/// RuntimeFailedError reports the runtime's terminal failed phase.
public struct RuntimeFailedError: Error, Equatable, Sendable {
    public let snapshot: PhaseSnapshot

    public init(snapshot: PhaseSnapshot) {
        self.snapshot = snapshot
    }
}

/// One version-exact length-prefixed session frame.
public struct SessionFrame: Sendable {
    public var kind: SessionFrameKind
    public var flags: SessionFrameFlags
    public var id: UInt64
    public var sequence: UInt32
    public var deadlineUnixMilliseconds: Int64
    public var operation: String
    public var tenant: String
    public var payload: Data

    public init(
        kind: SessionFrameKind,
        flags: SessionFrameFlags = [],
        id: UInt64 = 0,
        sequence: UInt32 = 0,
        deadlineUnixMilliseconds: Int64 = 0,
        operation: String = "",
        tenant: String = "",
        payload: Data = Data()
    ) {
        self.kind = kind
        self.flags = flags
        self.id = id
        self.sequence = sequence
        self.deadlineUnixMilliseconds = deadlineUnixMilliseconds
        self.operation = operation
        self.tenant = tenant
        self.payload = payload
    }
}

/// One ordered request-stream chunk.
public struct SocketRequestChunk: Sendable {
    public let sequence: UInt32
    public let payload: Data
    public let end: Bool
}

/// Errors raised while resolving or binding a unix-socket address.
enum SocketServerError: Error, Sendable {
    case pathTooLong(path: String, limit: Int)
    case addressInUse(path: String)
    case socketFailed(errno: Int32)
    case bindFailed(path: String, errno: Int32)
    case chmodFailed(path: String, errno: Int32)
    case listenFailed(errno: Int32)
    case alreadyRunning
}

/// Fail-closed codec errors.
public enum SessionTransportError: Error, Equatable, Sendable {
    case truncatedFrame
    case frameTooLarge(actual: Int, maximum: Int)
    case invalidFrame(String)
    case unsupportedProtocolVersion(UInt16)
    case systemCall(operation: String, errno: Int32)
    case handshake(String)
    case duplicateRequestID(UInt64)
    case streamSequence(id: UInt64, got: UInt32, want: UInt32)
    case cancellationDidNotSettle
    case disconnected
}

extension SessionTransportError {
    var isPeerEndWriteFailure: Bool {
        switch self {
        case .disconnected:
            true
        case let .systemCall(operation, code):
            operation == "send"
                && (code == EPIPE || code == ECONNRESET || code == ECONNABORTED || code == ENOTCONN)
        default:
            false
        }
    }
}

/// The server identity established by the mandatory protocol-2 handshake.
struct SessionWireIdentity: Sendable {
    let protocolVersion: UInt16
    let schema: String
    let session: Data
    let phase: SessionPhase
}

struct SessionHelloIdentity: Encodable, Sendable {
    let protocolVersion: UInt16
    let lane: SessionLane
    let schema: String?
    let nonce: Data?

    init(protocolVersion: UInt16, lane: SessionLane, schema: String? = nil, nonce: Data? = nil) {
        self.protocolVersion = protocolVersion
        self.lane = lane
        self.schema = schema
        self.nonce = nonce
    }

    enum CodingKeys: String, CodingKey {
        case protocolVersion = "protocol"
        case lane
        case schema
        case nonce
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(protocolVersion, forKey: .protocolVersion)
        try container.encode(lane, forKey: .lane)
        if let schema, !schema.isEmpty {
            try container.encode(schema, forKey: .schema)
        }
        if let nonce, !nonce.isEmpty {
            try container.encode(nonce.base64EncodedString(), forKey: .nonce)
        }
    }
}

enum SessionHandshakeCodec {
    static func decodeAck(_ data: Data) throws -> SessionWireIdentity {
        guard let object = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw SessionTransportError.handshake("invalid acknowledgment JSON")
        }
        guard let protocolNumber = object["protocol"] as? NSNumber else {
            throw SessionTransportError.handshake("acknowledgment protocol")
        }
        let protocolVersion = protocolNumber.uint16Value
        guard protocolVersion == daemonKitSessionProtocolVersion else {
            throw SessionTransportError.unsupportedProtocolVersion(protocolVersion)
        }
        guard let schema = object["schema"] as? String, !schema.isEmpty else {
            throw SessionTransportError.handshake("empty server schema")
        }
        guard let phaseRaw = object["phase"] as? String, let phase = SessionPhase(rawValue: phaseRaw) else {
            throw SessionTransportError.handshake("acknowledgment phase")
        }
        let rejected = (object["rejected"] as? NSNumber)?.boolValue ?? false
        if rejected {
            guard object["session"] == nil,
                  Set(object.keys).isSubset(of: ["protocol", "schema", "phase", "rejected", "code", "reason"]),
                  let rawCode = object["code"] as? String, !rawCode.isEmpty,
                  let reason = object["reason"] as? String, !reason.isEmpty
            else {
                throw SessionTransportError.handshake("invalid rejection")
            }
            let code = SocketResponseCode(rawValue: rawCode)
            switch code {
            case .sessionCapacity, .peerUntrusted, .buildMismatch:
                throw SocketHandshakeRejectionError(code: code, reason: reason)
            default:
                throw SessionTransportError.handshake("invalid rejection code \(rawCode.debugDescription)")
            }
        }
        guard object["code"] == nil, object["reason"] == nil else {
            throw SessionTransportError.handshake("success carried rejection")
        }
        guard Set(object.keys).isSubset(of: ["protocol", "schema", "session", "phase"]),
              let sessionRaw = object["session"] as? String,
              let session = Data(base64Encoded: sessionRaw),
              session.count == sessionGenerationBytes
        else {
            throw SessionTransportError.handshake("invalid session generation")
        }
        return SessionWireIdentity(
            protocolVersion: protocolVersion,
            schema: schema,
            session: session,
            phase: phase
        )
    }

    static func decodeLifecycle(_ data: Data) throws -> PhaseSnapshot {
        guard let object = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              Set(object.keys).isSubset(of: ["sequence", "phase", "detail"]),
              let sequence = object["sequence"] as? NSNumber,
              let phaseRaw = object["phase"] as? String,
              let phase = SessionPhase(rawValue: phaseRaw)
        else {
            throw SessionTransportError.invalidFrame("lifecycle snapshot")
        }
        let detail: Data? = if let value = object["detail"] {
            try JSONSerialization.data(withJSONObject: value, options: [.fragmentsAllowed])
        } else {
            nil
        }
        return PhaseSnapshot(sequence: sequence.uint64Value, phase: phase, detail: detail)
    }
}

let sessionGenerationBytes = 16

struct SessionSequence: Sendable {
    private var next: UInt32
    private var exhausted = false

    init(next: UInt32 = 0) {
        self.next = next
    }

    mutating func take() throws -> UInt32 {
        guard !exhausted else {
            throw SessionTransportError.invalidFrame("stream sequence exhausted")
        }
        let value = next
        if next == .max {
            exhausted = true
        } else {
            next += 1
        }
        return value
    }
}

final class SessionFrameCodec: @unchecked Sendable {
    static let defaultMaximumFrameBytes = daemonKitDefaultMaximumFrameBytes
    /// The two bytes 0x4452 ("DR") a draining server emits instead of an ack.
    static let drainPreamble = Data([0x44, 0x52])

    private let descriptor: Int32
    private let maximumFrameBytes: Int
    private let writeTimeout: TimeInterval
    private let writeLock = NSLock()
    private var peeked: Data?

    init(
        descriptor: Int32,
        maximumFrameBytes: Int = defaultMaximumFrameBytes,
        writeTimeout: TimeInterval = 0
    ) {
        self.descriptor = descriptor
        self.maximumFrameBytes = maximumFrameBytes
        self.writeTimeout = writeTimeout
    }

    /// Reads the next two bytes and reports whether they are the drain preamble.
    /// Bytes that are not the preamble are stashed as the head of the next frame
    /// read, mirroring internal/wire.Codec.PeekPreamble.
    func peekPreamble(timeout: TimeInterval = 0) throws -> Bool {
        let head = try readExactly(2, deadline: Self.deadline(after: timeout))
        if head == Self.drainPreamble {
            return true
        }
        peeked = head
        return false
    }

    func read(timeout: TimeInterval = 0) throws -> SessionFrame {
        let deadline = Self.deadline(after: timeout)
        let prefix = try readExactly(4, deadline: deadline)
        let length = Int(prefix.uint32(at: 0))
        guard length <= maximumFrameBytes else {
            throw SessionTransportError.frameTooLarge(actual: length, maximum: maximumFrameBytes)
        }
        guard length >= Self.headerBytes else {
            throw SessionTransportError.invalidFrame("body length \(length)")
        }
        return try Self.decode(readExactly(length, deadline: deadline))
    }

    func write(_ frame: SessionFrame) throws {
        let packet = try encodedPacket(frame)
        writeLock.lock()
        defer { writeLock.unlock() }
        try writeAll(packet, deadline: Self.deadline(after: writeTimeout))
    }

    func write(
        _ frame: SessionFrame,
        passing descriptorToPass: Int32,
        deadline wallDeadline: Date,
        onDescriptorSent: () -> Void
    ) throws {
        guard descriptorToPass >= 0 else {
            throw SessionTransportError.invalidFrame("invalid passed descriptor")
        }
        let packet = try encodedPacket(frame)
        let remaining = wallDeadline.timeIntervalSinceNow
        guard remaining > 0 else {
            throw SessionTransportError.systemCall(operation: "sendmsg", errno: ETIMEDOUT)
        }
        let deadline = Self.deadline(after: min(writeTimeout, remaining))
        writeLock.lock()
        defer { writeLock.unlock() }
        let written = try sendPrefix(packet.prefix(4), passing: descriptorToPass, deadline: deadline)
        onDescriptorSent()
        try writeAll(Data(packet.dropFirst(written)), deadline: deadline)
    }

    private func encodedPacket(_ frame: SessionFrame) throws -> Data {
        let body = try Self.encode(frame)
        guard body.count <= maximumFrameBytes else {
            throw SessionTransportError.frameTooLarge(actual: body.count, maximum: maximumFrameBytes)
        }
        var packet = Data()
        packet.appendUInt32(UInt32(body.count))
        packet.append(body)
        return packet
    }
}

extension SessionFrameCodec {
    private static func validate(_ frame: SessionFrame) throws {
        guard frame.flags.subtracting(.end).isEmpty else {
            throw SessionTransportError.invalidFrame("unknown flags")
        }
        switch frame.kind {
        case .hello, .helloAck:
            try require(
                frame.flags == .end && frame.id == 0 && frame.sequence == 0 &&
                    frame.deadlineUnixMilliseconds == 0 && frame.operation.isEmpty &&
                    frame.tenant.isEmpty && !frame.payload.isEmpty,
                "handshake frame"
            )
        case .request:
            try require(
                frame.id != 0 && frame.sequence == 0 && frame.deadlineUnixMilliseconds >= 0 &&
                    !frame.operation.isEmpty,
                "request frame"
            )
        case .response:
            try require(
                frame.flags == .end && frame.id != 0 && frame.sequence == 0 &&
                    frame.deadlineUnixMilliseconds == 0 && frame.operation.isEmpty &&
                    frame.tenant.isEmpty && !frame.payload.isEmpty,
                "response frame"
            )
        case .cancel:
            try require(
                frame.flags == .end && frame.id != 0 && frame.sequence == 0 &&
                    frame.deadlineUnixMilliseconds == 0 && frame.operation.isEmpty &&
                    frame.tenant.isEmpty && frame.payload.isEmpty,
                "cancel frame"
            )
        case .event:
            try require(
                frame.flags == .end && frame.id == 0 && frame.sequence == 0 &&
                    frame.deadlineUnixMilliseconds == 0 && !frame.operation.isEmpty &&
                    frame.tenant.isEmpty,
                "event frame"
            )
        case .stream:
            try require(
                frame.id != 0 && frame.deadlineUnixMilliseconds == 0 &&
                    frame.operation.isEmpty && frame.tenant.isEmpty,
                "stream frame"
            )
        case .goAway:
            try require(
                frame.flags == .end && frame.id == 0 && frame.sequence == 0 &&
                    frame.deadlineUnixMilliseconds == 0 && frame.operation.isEmpty &&
                    frame.tenant.isEmpty && frame.payload.isEmpty,
                "go-away frame"
            )
        case .window:
            try require(
                frame.flags.isEmpty && frame.sequence > 0 && frame.deadlineUnixMilliseconds == 0 &&
                    frame.operation.isEmpty && frame.tenant.isEmpty && frame.payload.isEmpty,
                "window frame"
            )
        case .acknowledgment:
            try require(
                frame.flags == .end && frame.id != 0 && frame.sequence == 0 &&
                    frame.deadlineUnixMilliseconds == 0 && frame.operation.isEmpty &&
                    frame.tenant.isEmpty && frame.payload.count == 16,
                "acknowledgement frame"
            )
        case .lifecycle:
            try require(
                frame.flags == .end && frame.id == 0 && frame.sequence == 0 &&
                    frame.deadlineUnixMilliseconds == 0 && frame.operation.isEmpty &&
                    frame.tenant.isEmpty && !frame.payload.isEmpty,
                "lifecycle frame"
            )
        }
    }

    private static func require(_ condition: @autoclosure () -> Bool, _ reason: String) throws {
        guard condition() else { throw SessionTransportError.invalidFrame(reason) }
    }

    private func readExactly(_ count: Int, deadline: UInt64?) throws -> Data {
        var data = Data(count: count)
        var offset = 0
        if let stashed = peeked {
            peeked = nil
            if stashed.count >= count {
                let head = Data(stashed.prefix(count))
                let rest = stashed.dropFirst(count)
                if !rest.isEmpty {
                    peeked = Data(rest)
                }
                return head
            }
            data.replaceSubrange(0 ..< stashed.count, with: stashed)
            offset = stashed.count
        }
        while offset < count {
            let readCount = data.withUnsafeMutableBytes { buffer in
                Darwin.read(descriptor, buffer.baseAddress?.advanced(by: offset), count - offset)
            }
            if readCount == 0 {
                if offset == 0 {
                    throw SessionTransportError.disconnected
                }
                throw SessionTransportError.truncatedFrame
            }
            if readCount < 0 {
                if errno == EINTR {
                    continue
                }
                if errno == EAGAIN || errno == EWOULDBLOCK {
                    try waitUntilReady(events: Int16(POLLIN), operation: "read", deadline: deadline)
                    continue
                }
                throw SessionTransportError.systemCall(operation: "read", errno: errno)
            }
            offset += readCount
        }
        return data
    }

    private func writeAll(_ data: Data, deadline: UInt64?) throws {
        var offset = 0
        while offset < data.count {
            let written = data.withUnsafeBytes { buffer in
                Darwin.send(
                    descriptor,
                    buffer.baseAddress?.advanced(by: offset),
                    data.count - offset,
                    MSG_NOSIGNAL
                )
            }
            if written < 0 {
                if errno == EINTR {
                    continue
                }
                if errno == EAGAIN || errno == EWOULDBLOCK {
                    try waitUntilReady(events: Int16(POLLOUT), operation: "send", deadline: deadline)
                    continue
                }
                throw SessionTransportError.systemCall(operation: "send", errno: errno)
            }
            if written == 0 {
                throw SessionTransportError.truncatedFrame
            }
            offset += written
        }
    }

    private func sendPrefix(
        _ prefix: Data.SubSequence,
        passing descriptorToPass: Int32,
        deadline: UInt64?
    ) throws -> Int {
        guard prefix.count == 4 else {
            throw SessionTransportError.invalidFrame("descriptor handoff prefix")
        }
        let headerBytes = MemoryLayout<cmsghdr>.size
        let controlBytes = headerBytes + MemoryLayout<Int32>.size
        let control = UnsafeMutableRawPointer.allocate(
            byteCount: controlBytes,
            alignment: MemoryLayout<cmsghdr>.alignment
        )
        defer { control.deallocate() }
        control.initializeMemory(as: UInt8.self, repeating: 0, count: controlBytes)
        let header = control.assumingMemoryBound(to: cmsghdr.self)
        header.pointee.cmsg_len = UInt32(controlBytes)
        header.pointee.cmsg_level = SOL_SOCKET
        header.pointee.cmsg_type = SCM_RIGHTS
        control.advanced(by: headerBytes).storeBytes(of: descriptorToPass, as: Int32.self)

        while true {
            let written = prefix.withUnsafeBytes { bytes -> Int in
                var vector = iovec(
                    iov_base: UnsafeMutableRawPointer(mutating: bytes.baseAddress),
                    iov_len: bytes.count
                )
                return withUnsafeMutablePointer(to: &vector) { vectorPointer in
                    var message = msghdr()
                    message.msg_iov = vectorPointer
                    message.msg_iovlen = 1
                    message.msg_control = control
                    message.msg_controllen = UInt32(controlBytes)
                    return Darwin.sendmsg(descriptor, &message, MSG_NOSIGNAL)
                }
            }
            if written > 0 {
                return written
            }
            if written == 0 {
                throw SessionTransportError.truncatedFrame
            }
            if errno == EINTR {
                continue
            }
            if errno == EAGAIN || errno == EWOULDBLOCK {
                try waitUntilReady(events: Int16(POLLOUT), operation: "sendmsg", deadline: deadline)
                continue
            }
            throw SessionTransportError.systemCall(operation: "sendmsg", errno: errno)
        }
    }

    private func waitUntilReady(events: Int16, operation: String, deadline: UInt64?) throws {
        while true {
            var descriptor = pollfd(fd: descriptor, events: events, revents: 0)
            let ready = poll(&descriptor, 1, Self.pollTimeout(deadline: deadline))
            if ready > 0 {
                return
            }
            if ready == 0 {
                throw SessionTransportError.systemCall(operation: operation, errno: ETIMEDOUT)
            }
            // EAGAIN: poll(2) failed to allocate internal data structures — a
            // documented retriable transient, bounded by the same deadline.
            if errno == EINTR || errno == EAGAIN {
                continue
            }
            throw SessionTransportError.systemCall(operation: "poll", errno: errno)
        }
    }

    static func deadline(after timeout: TimeInterval) -> UInt64? {
        guard timeout > 0 else { return nil }
        let nanoseconds = timeout * 1_000_000_000
        guard nanoseconds < Double(UInt64.max) else { return UInt64.max }
        let now = DispatchTime.now().uptimeNanoseconds
        let duration = UInt64(nanoseconds.rounded(.up))
        let (deadline, overflow) = now.addingReportingOverflow(duration)
        return overflow ? UInt64.max : deadline
    }

    static func pollTimeout(deadline: UInt64?, maximum: Int32 = .max) -> Int32 {
        guard let deadline else { return -1 }
        let now = DispatchTime.now().uptimeNanoseconds
        guard deadline > now else { return 0 }
        let remaining = deadline - now
        let milliseconds = remaining / 1_000_000 + (remaining % 1_000_000 == 0 ? 0 : 1)
        return Int32(min(milliseconds, UInt64(maximum)))
    }

    static func durationNanoseconds(_ timeout: TimeInterval) -> UInt64 {
        guard timeout > 0 else { return 0 }
        let nanoseconds = timeout * 1_000_000_000
        guard nanoseconds.isFinite, nanoseconds < Double(UInt64.max) else { return .max }
        return UInt64(nanoseconds.rounded(.up))
    }
}

private extension Data {
    mutating func appendUInt16(_ value: UInt16) {
        var bigEndian = value.bigEndian
        Swift.withUnsafeBytes(of: &bigEndian) { append(contentsOf: $0) }
    }

    mutating func appendUInt32(_ value: UInt32) {
        var bigEndian = value.bigEndian
        Swift.withUnsafeBytes(of: &bigEndian) { append(contentsOf: $0) }
    }

    mutating func appendUInt64(_ value: UInt64) {
        var bigEndian = value.bigEndian
        Swift.withUnsafeBytes(of: &bigEndian) { append(contentsOf: $0) }
    }

    func uint16(at offset: Int) -> UInt16 {
        withUnsafeBytes { UInt16(bigEndian: $0.loadUnaligned(fromByteOffset: offset, as: UInt16.self)) }
    }

    func uint32(at offset: Int) -> UInt32 {
        withUnsafeBytes { UInt32(bigEndian: $0.loadUnaligned(fromByteOffset: offset, as: UInt32.self)) }
    }

    func uint64(at offset: Int) -> UInt64 {
        withUnsafeBytes { UInt64(bigEndian: $0.loadUnaligned(fromByteOffset: offset, as: UInt64.self)) }
    }
}
