// Code generated by wire/lifeproto/gen; DO NOT EDIT.

package lifeproto

import (
	"encoding/json"
	"errors"
	"fmt"
)

// Version is the lifecycle protocol version carried in every envelope's "v"
// field. The Swift peer pins the same constant.
const Version = 1

// The op strings name each lifecycle operation. Frozen wire values.
const (
	OpHealth   = "health"
	OpShutdown = "shutdown"
	OpHandoff  = "handoff"
)

// ErrProtocolVersion means a decoded envelope carried a "v" other than Version.
var ErrProtocolVersion = errors.New("lifeproto: unsupported protocol version")

// Envelope is the {v, op} header every message begins with; ReadEnvelope decodes
// it to dispatch on Op before the concrete request type is known.
type Envelope struct {
	V  int    `json:"v"`
	Op string `json:"op"`
}

// HealthRequest asks the peer for its health snapshot.
type HealthRequest struct {
	V  int    `json:"v"`
	Op string `json:"op"`
}

// NewHealthRequest builds a health request at the current protocol version.
func NewHealthRequest() HealthRequest {
	return HealthRequest{V: Version, Op: OpHealth}
}

// HealthResponse is the peer's exact-protocol health snapshot.
type HealthResponse struct {
	V        int    `json:"v"`
	Op       string `json:"op"`
	Build    string `json:"build"`
	Protocol int    `json:"protocol"`
	PID      int    `json:"pid"`
	State    string `json:"state"`
	Draining bool   `json:"draining"`
	Busy     bool   `json:"busy"`
}

// NewHealthResponse builds a health snapshot.
func NewHealthResponse(build string, protocolVersion int, pid int, state string, draining bool, busy bool) HealthResponse {
	return HealthResponse{V: Version, Op: OpHealth, Build: build, Protocol: protocolVersion, PID: pid, State: state, Draining: draining, Busy: busy}
}

// ShutdownRequest asks the peer to shut down.
type ShutdownRequest struct {
	V  int    `json:"v"`
	Op string `json:"op"`
}

// NewShutdownRequest builds a shutdown request.
func NewShutdownRequest() ShutdownRequest {
	return ShutdownRequest{V: Version, Op: OpShutdown}
}

// ShutdownResponse acknowledges a shutdown request.
type ShutdownResponse struct {
	V  int    `json:"v"`
	Op string `json:"op"`
	OK bool   `json:"ok"`
}

// NewShutdownResponse builds a shutdown acknowledgement.
func NewShutdownResponse(ok bool) ShutdownResponse {
	return ShutdownResponse{V: Version, Op: OpShutdown, OK: ok}
}

// HandoffRequest asks the peer to release its socket for a successor.
type HandoffRequest struct {
	V  int    `json:"v"`
	Op string `json:"op"`
}

// NewHandoffRequest builds a handoff request.
func NewHandoffRequest() HandoffRequest {
	return HandoffRequest{V: Version, Op: OpHandoff}
}

// HandoffResponse acknowledges a handoff request.
type HandoffResponse struct {
	V  int    `json:"v"`
	Op string `json:"op"`
	OK bool   `json:"ok"`
}

// NewHandoffResponse builds a handoff acknowledgement.
func NewHandoffResponse(ok bool) HandoffResponse {
	return HandoffResponse{V: Version, Op: OpHandoff, OK: ok}
}

// Encode marshals one lifecycle message for a v1 request or response payload.
func Encode(msg any) ([]byte, error) {
	b, err := json.Marshal(msg)
	if err != nil {
		return nil, fmt.Errorf("lifeproto: encode: %w", err)
	}
	return b, nil
}

// DecodeEnvelope decodes {v, op} and rejects every foreign protocol version.
func DecodeEnvelope(b []byte) (Envelope, error) {
	var e Envelope
	if err := json.Unmarshal(b, &e); err != nil {
		return Envelope{}, fmt.Errorf("lifeproto: decode envelope: %w", err)
	}
	if e.V != Version {
		return Envelope{}, fmt.Errorf("%w: got v=%d, want %d", ErrProtocolVersion, e.V, Version)
	}
	return e, nil
}
