#!/bin/sh
# Regenerate the frame codec from internal/wiregen/schema.json and fail when
# the checked-in Go (internal/wire/frame.go) or Swift (SessionFrameCodec
# section of SessionTransport.swift) output drifts, so a hand-edit of
# generated code or an un-regenerated schema change goes red. On drift the
# regenerated bytes are left in place; the diff below is the fix to commit.
set -eu

cd "$(dirname "$0")/.."
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
cp internal/wire/frame.go "$tmp/frame.go"
cp Sources/DaemonKit/SessionTransport.swift "$tmp/SessionTransport.swift"
go generate ./internal/wire
status=0
diff -u "$tmp/frame.go" internal/wire/frame.go || status=1
diff -u "$tmp/SessionTransport.swift" Sources/DaemonKit/SessionTransport.swift || status=1
if [ "$status" -ne 0 ]; then
  echo "check-codegen: generated frame codec drifted from internal/wiregen/schema.json; run 'task generate' and commit" >&2
fi
exit "$status"
